### ISSUE TITLE
Support the literal "." with escaping

### ISSUE THREAD

**Issue by dhaspden** [dhaspden/transmog#1]
### Features:

Currently maps with keys which have the period character in them are not mapped as you'd expect. We should support the period character by allowing it to be escaped. Escaped periods will not trigger the split in `Transmog.Parser`.

Examples:

```elixir
iex> Transmog.Parser.parse([{"a\.b", "b\.a"}])
[{["a.b", "b.a"}]
```

**Comment by zpeters** [comment]
i would like to take a look at this

**Comment by dhaspden** [comment]
@zpeters I'm always accepting PRs 😃

**Comment by zpeters** [comment]
made a little progress, not as easy as it seems

**Comment by dhaspden** [comment]
I think it likely revolves around having to change the parser to match based on a regular expression instead of just doing a string split. I think the regular expression is a better way to go anyway because we can introduce different syntax later if we need it :+1:

If I have some downtime tonight maybe I can take a look and give you some pointers!

**Comment by zpeters** [comment]
It looks liek the problem i'm running into is that elixir is taking the "\." in my testing strings and treating the "\." as a ".".   I have figured out how to do a regex split and a negative look behind that will ignore "\." but i can't figure out how to literally pass the string over.

See examples

Regex example: https://regex101.com/r/l483TJ/1

Code Snippets: 
- test and code - https://gist.github.com/zpeters/ce5d275ce8ad90bb5485b2160f7d2828
- output - https://gist.github.com/zpeters/4f0e7007dbbbdc661aeaba5ac328c145

**Comment by dhaspden** [comment]
I think it's likely because Elixir makes you escape the backslash with another backslash. So if we wanted to go that route we'd have to use a double backslash. Maybe give that a shot and see how it works out?

```
key_mapping = [{"a\\.b", "b\\.a"}]
```

**Comment by dhaspden** [comment]
This should be ready, check out master and let me know if you can break it 😄

**Comment by zpeters** [comment]
This is great.  Cheers
